### ISSUE TITLE
Undead Brute & Undead Stalker - Missing AC Item Bonus & Dexterity Cap

### ISSUE THREAD

**Issue by 7H3LaughingMan** [TikaelSol/PF2e-Animal-Companions#69]
It looks like both options for Undead Eidolons are missing the AC Item Bonus and Dexterity Cap

**Comment by TikaelSol** [comment]
They sure are. But that's not really my mistake to fix, since it's an issue in the source material. If you can find anywhere that Paizo has clarified it I'll fix it. AoN just followed the pattern from other eidolons for their numbers.

![image](https://github.com/TikaelSol/PF2e-Animal-Companions/assets/80183198/16040098-cb09-4e51-ac31-c2eac2b36502)
