### ISSUE TITLE
Ability scores are very sensitive/buggy

### ISSUE THREAD

**Issue by m0stlyh4rmless** [TikaelSol/PF2e-Animal-Companions#7]
It seems like the script to add the ability scores will re-add them whenever a change is made to the scores (or level, and maybe some other strange sheet interactions)
Increasing the sheet's level or editing an ability score will repeat the ability score buffs/nerfs that the script initially does, making it impossible to correct this bug without deleting the sheet entirely and starting again.

**Comment by TikaelSol** [comment]
This is a known issue with the "add" active effect.  It's something that can't be fixed from the module side since the module just hooks into the system's built in active effects, but it is fixed in the dev version of the PF2e system and the fix should be included with the 2.0.4 update which will hopefully be out as soon as some other bugs in the release are taken care of.
